# Netlify Configuration for Frontend
[build]
  command = "npm run build"
  publish = "dist"
  
[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables (set in Netlify dashboard)
# VITE_API_URL = your_backend_url/api
# VITE_SOCKET_URL = your_backend_url
